template: configs/config_finetune_pinkcc_unet.yaml

wandb:
  entity: nationaltaiwanuniversity
  project: PINKCC
  group: UNet

configuration:
  name: SuPrem-UNet
  method: bayes
  metric:
    goal: maximize
    name: test_meandice
  parameters:
    epochs:
      values: [200, 400, 600, 800]
    base_lr:
      min: 1e-5
      max: 1e-3
    warmup_epochs:
      values: [10, 20, 25, 50]
    weight_decay:
      values: [1e-4, 1e-5, 1e-6]
    
