template: configs/config_finetune_pinkcc_segresnet.yaml

wandb:
  entity: nationaltaiwanuniversity
  project: PINKCC
  group: RandCropbyLabelClasses

configuration:
  name: SuPrem-SegResNet
  method: bayes
  metric:
    goal: maximize
    name: test_meandice
  parameters:
    ratios:
      values: [[1, 3, 1], [1, 3, 2], [1, 3, 3], [1, 3, 4]]
    
