from nvcr.io/nvidia/pytorch:21.11-py3

RUN pip install -U pip && \
    pip install monai[all]==0.7.0 pytorch-lightning>=1.5.0 nvflare>=2.0.0

COPY . /opt/manafaln
RUN cd /opt/manafaln && \
    python setup.py install && \
    rm -rf /workspace/* && \
    cp -r /opt/manafaln/examples /workspace/examples
